### ISSUE TITLE
Could you provide the code of L1000 datasets??

### ISSUE THREAD

**Issue by matsutakk** [mfbalin/Concrete-Autoencoders#5]
Hello, I've read your paper and I would like to do a experiment of L1000 datasets.
I checked [this site ](http://lincsportal.ccs.miami.edu/datasets/?query=assayname:L1000%20mRNA%20profiling%20assay]), but there are seven datasets. 

Whick datasets did you use??
And, Could you provide the code of processing datasets??

Thank you.

**Comment by mfbalin** [comment]
Please contact the authors of this work: https://github.com/uci-cbcl/D-GEX

**Comment by matsutakk** [comment]
Thank you very much!
